# Generated by Django 4.2.7 on 2023-11-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_diplom', '0002_worker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_diplom.company'),
        ),
    ]
